Ideal-Media-Solutions-LLC/buskr

- src/components/search/Search.jsx
Create seach folder under components, add search.jsx file
> create search component root

- src/components/calendar/CalendarView.jsx
- src/styles/Calendar.css
Polished the CSS further so now it matches the wireframe and overall style.
- Fixed the oval selection to circle
- Removed the hidden built-in dotted line under weekdays
- Fixed the glitch-like click experience by setting the active days to the Buskr-pink.
- Hid the year arrows (double arrows) from the component
- Updated the arrows to custom react-icon components
- Changed the colors according to wireframe and using the Buskr variables
@jonathanjewett - Teammate
@c4mino - Code Review
Please review this for me, thank you Michael :D
> Polished Calendar CSS

- next.config.js
- src/components/map/Map.jsx
- src/styles/map.module.css
I changed the strategy for positioning the infobox overlay.  There is still some funkiness with styling the caption, but that will be fixed later.  Currently the caption lists the event name followed by the busker's name on the next line.  I am open to suggestions of what other data should be displayed on the card.
> Map infobox

- src/components/profile/Profile.jsx
- src/pages/index.js
Small PR to preserve work on GET Request for `<Profile />` component.
@ygroener @apriljgranzow
> GET request and data flow begun for Profile component

- src/components/create-event/CreateEvent.jsx
- src/components/map/Map.jsx
- src/styles/map.module.css
The map is now viewable on the event creation form.  
I refactored the map component in order for it to be included on any page.  It now takes the following props:
- `containerStyle`: takes an inline styling object to determine the size of the map view on the page.  
- For example:
- `const containerStyle = { height: '70vh' };`
- ` const mapContainerStyle = { height: '300px', width: 'auto'}`
- `center`: takes an object with properties `lat` and `lng`:
- `const center = { lng: -90.06911208674771, lat: 29.954767355989652};`
- `withInfoBoxes` can be `true` or `false`, if set to `true` it will display an infobox upon clicking on a marker.
> Integrating map component with event creation form

- src/components/profile/Profile.jsx
- src/styles/Profile.module.css
- src/styles/resultList.module.css
Name, photo, bio, and events render dynamically from database. Event Items render using `<EventItem />` component.
etc's: @roheunji resultList.module.css altered to give eventItem details such as name, date, busker, their color properties directly instead of inherited from activeTab class.
@jnbooth @apriljgranzow please review at your earliest convenience, thank you!
> Profile dynamic rendering

- package.json
- src/components/create-event/CreateEvent.jsx
- src/components/profile/Profile.jsx
- src/pages/create.js
- src/pages/index.js
- src/pages/profile/[id].js
Profile URLs now dynamically render `<Profile id={id}/>` at /profile/:id.
/create now renders Create Event landing page. Clicking Next button stores user inputs into state and renders the next page for creating an event.
**To Do:** add Upload Image feature
etc's: please re-run npm i for react-image-upload dependency.
@ygroener nice work Yosef!
@jnbooth @apriljgranzow please review at your earlier convenience.
> Profile and Event routing

- docs/API_DOCS.md
- Updated API_DOCS.md to Josh's API documentation
@apriljgranzow @jnbooth - Code Review
Thanks!
> Updated API_DOCS.md to our API Endpoints Doc.

- package.json
- src/styles/Search.module.css
Switched dependencies for image uploading, please re-run npm i.
Minor css change to Search.module.css for app-wide visual consistency
> npm switch to react-images-uploading, css fix

- src/components/create-event/CreateEvent.jsx
- src/styles/CreateEvent.module.css
The work for this PR was done for the first page of event creation.
Main additions were adding working input and state for event times and dates.
I also added simple validation for each input field which is tested when Next is clicked.
This screen shot is of the wire frames
If you look at this gif you can see, I combined the time and date inputs into one.
https://user-images.githubusercontent.com/84756768/145951821-4a38b077-258a-44bf-9938-0d33e5f4ab4b.mp4
I used react-date-picker for the Date and Time choosing.
I added validation using the CSS hidden property and some ternary operators.
- This PR allows users to choose the start and end event times and dates for their performances. 
- This is stored in state and will be submitted as part of the event object upon form submission.
- Added …
> Event Creation Page 1

- .env
- src/components/map/Map.jsx
- src/styles/Map.module.css
- Infobox is no longer prevented from displaying due to a typo
- Infobox displays event date and time
- Event name links to its page
- Busker name links to their profile page
- Corrected a syntax error (extra semicolon) that was causing the CSS module to silently fail
- Improved element styling
> Improve infobox styling and functionality

- src/components/search/Search.jsx
- src/components/search/SearchSection.jsx
- src/components/search/results/EventItem.jsx
- src/components/search/results/EventList.jsx
- src/styles/resultList.module.css
When a user enters the site, it renders a list for current location and current date.
When a user searches for a name, performer, or tag, it renders a list based on the input.
When a user searches for a date, it renders a list based on input.
- it sends a get request when it renders
- the default date and location is based the browser
- it sort by soonest
- filter events of searched list from keys
@mkr123 - Teammate
> Search Functionality

- src/components/search/SearchSection.jsx
- src/components/search/results/EventList.jsx
- src/styles/resultList.module.css
When a user clicks on a tag, the list will rendered based on the tag.
-  clicking on starting soon tag will filter the list for the current day by time
-  clicking on tomorrow tag will filter the list for the next day by distance
-  clicking on near you tag will filter the list that has event with a distance less than 100
-  clicking on other tags will filter the list by what you clicked on for the current day
-  if the event list is empty, it will render stating 'no events'
@mkr123  - teammate
Thank you!
> Clicking tags function

- src/components/calendar/CalendarView.jsx
- src/components/search/Search.jsx
- src/components/search/SearchSection.jsx
- src/components/search/results/EventItem.jsx
- src/components/search/results/TabViews.jsx
When the user clicks on the calendar view, it renders a calendar with the list of events
- added links to that it routes to the profile and event details page
- added context that contains a state that calendar view can use
- add the calendar view component to the tab so that it renders
branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()
@mkr123  - Teammate
@apriljgranzow @jonathandavidlewis @chiaolinghong3d 
Thanks!
> Link with Calendar View

- src/components/search/SearchSection.jsx
- src/styles/Search.module.css
**CSS Update for Mini Search Bar**
Styling change for app consistency, border style/colors/focus
**BEFORE**
**AFTER**
> mini search bar css consistency update

- src/components/calendar/CalendarView.jsx
- src/components/search/Autocomplete.jsx
- src/components/search/Search.jsx
- src/components/search/SearchSection.jsx
- src/components/search/results/TabViews.jsx
- src/styles/Search.module.css
- Add calendar component to search tabview area
- Create context for calendar. so calendar date onClick function can interact with search component
- Change search input to autocomplete component, show different placeholder for mini searchbar
@c4mino - create autocomplete component css, helped a lot on css styling
@roheunji -teammate
> Search kerry

- README.md
- migrations/20211216000120-payments.js
- migrations/sqls/20211216000120-payments-down.sql
- migrations/sqls/20211216000120-payments-up.sql
- seed.js
- src/components/calendar/CalendarView.jsx
- src/components/create-event/CreateEvent.jsx
- src/components/search/SearchSection.jsx
- src/db/busker.js
Note: wait until this is actually merged before doing any of these steps. Before setting up, remove everything from your .env.local file except what I sent in chat today. If you have any problems with this process, let me know. Making sure this works for everyone is my top priority by far.
Copied from the new README.md:
- [Node.js](nodejs.org)
- [PostgreSQL](postgresql.org)
- [PostGIS](postgis.net)
- [Redis](redis.io)
1. Install all prerequisites and make sure services are running. **Do not proceed to step 2 until you have installed all four prerequisites.**
If you are using Mac OS X, [brew](https://brew.sh/) can install these dependencies for you. For example, to install and start Redis on a Mac:
```sh
brew install redis
brew services start redis
```
If you are using Windows, things are …
> Personal databases

- src/pages/create.js
This was just a small error with how Context.Subscriber works in functional components.
> Fix /create context bug

- src/components/Event.jsx
- src/components/create-event/CreateEvent.jsx
- src/components/search/results/EventItem.jsx
- src/styles/CreateEvent.module.css
- src/styles/Event.module.css
- src/styles/Map.module.css
- src/styles/Profile.module.css
- src/styles/globals.css
- src/styles/resultList.module.css
This is the layout change I demoed in Zoom.
> Dynamic height

- src/components/profile/Profile.jsx
- src/components/search/SearchSection.jsx
- src/pages/create.js
- src/styles/Profile.module.css
Josh Adjusted how context is working for profile so that will fix Michael's bug.
Changed payment icons to pull usernames from database
Clicking add my event links to event creation page.
Still have to update the link for QR Code
Thanks
> Tips and QR

- src/components/profile/Profile.jsx
- src/styles/Profile.module.css
Just a minor fix for QR code page set up
> re-sized and centered QR page

- src/auth.js
- src/db/busker.js
The image is retrieved every time the user logs in and displayed in their profile.
> Get user profile images from Google

- src/components/search/SearchSection.jsx
- src/pages/api/search.js
- src/styles/Search.module.css
- change tab button layout to center as we discussed during stand down
- turn off mini search bar autocomplete due to its css not work well
- add search by location result when location is not empty
@roheunji -teammate
> Search - some small changes

- src/components/search/SearchSection.jsx
- clicking on dance and magic will render a list of events with dance and magic
- change the tags to match the tags in db
> Change the tags to match

- src/components/profile/Profile.jsx
- src/styles/globals.css
Hi this PR added a missing '/' to make the QR code link work on profile pages.
Also added on hover to master button
> Profile finish
